In [19]:
import pandas as pd
import os

dataPath = os.getcwd() + '\\files'

In [24]:
df = pd.read_csv(dataPath + '\\cars.csv')
df.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197

In [27]:
df.dtypes

Make            object
Model           object
Type            object
Origin          object
DriveTrain      object
MSRP            object
Invoice         object
EngineSize     float64
Cylinders      float64
Horsepower       int64
MPG_City         int64
MPG_Highway      int64
Weight           int64
Wheelbase        int64
Length           int64
dtype: object

## Use the assign method
Convert the MSRP and Invoice columns to numeric. Use the original dataframe column values.

In [55]:
(df
 .assign(
         MSRP = df.MSRP.str.replace('$','', regex=True).str.replace(',','', regex=True).astype('int'),
         Invoice = df.Invoice.str.replace('$','', regex=True).str.replace(',','', regex=True).astype('int')
        )
)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186

## Use a lambda function within the assign method
The lambda function uses the intermediate dataframe

In [57]:
(df
 .assign(
         MSRP = lambda _df: _df.MSRP.str.replace('$','', regex=True).str.replace(',','', regex=True).astype('int'),
         Invoice = lambda _df:_df.Invoice.str.replace('$','', regex=True).str.replace(',','', regex=True).astype('int')
        )
)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186

## Use a user function within the assign method

In [53]:
def makeNumber(_df, colName):
    return (_df[colName]
            .str.replace('$','', regex=True)
            .str.replace(',','', regex=True)
            .astype('int')
    )

(df
 .assign(
         MSRP = makeNumber(df,'MSRP'),
         Invoice = makeNumber(df,'Invoice')
        )
)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186

## Use a user function in the assign method within a lambda function

In [59]:
def makeNumber(_df, colName):
    return (_df[colName]
            .str.replace('$','', regex=True)
            .str.replace(',','', regex=True)
            .astype('int')
    )

(df
 .assign(
         MSRP = lambda _df:  makeNumber(_df,'MSRP'),
         Invoice = lambda _df: makeNumber(_df,'Invoice')
        )
)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186

## Use the intermdiate dataframe in assign to calculate values

Try and subtract the new numeric Invoice and MSRP columns.

1. Start by checking with value will be used since the original columns are overwritten. Notice using the df.MSRP using the ORIGINAL MSRP column.

In [72]:
def makeNumber(_df, colName):
    return (_df[colName]
            .str.replace('$','', regex=True)
            .str.replace(',','', regex=True)
            .astype('int')
    )

(df
 .assign(
         MSRP = makeNumber(df,'MSRP'),
         Invoice = makeNumber(df,'Invoice'),
         PriceDiff = df.MSRP
        )
)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,PriceDiff
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189,"$36,945"
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172,"$23,820"
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183,"$26,990"
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186,"$33,195"
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197,"$43,755"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186,"$40,565"
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186,"$42,565"
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190,"$45,210"
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180,"$26,135"
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186,"$35,145"

2. Using a lambda function in the assign method pulls the intermediate dataframe value. In this case the numeric value in the MSRP column.

In [75]:
def makeNumber(_df, colName):
    return (_df[colName]
            .str.replace('$','', regex=True)
            .str.replace(',','', regex=True)
            .astype('int')
    )

(df
 .assign(
         MSRP = makeNumber(df,'MSRP'),
         Invoice = makeNumber(df,'Invoice'),
         PriceDiff = lambda _df: _df.MSRP
        )
)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,PriceDiff
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189,36945
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172,23820
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183,26990
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186,33195
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197,43755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186,40565
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186,42565
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190,45210
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180,26135
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186,35145

3. Calculate the price difference between MSRP and Invoice.

In [76]:
def makeNumber(_df, colName):
    return (_df[colName]
            .str.replace('$','', regex=True)
            .str.replace(',','', regex=True)
            .astype('int')
    )

(df
 .assign(
         MSRP = makeNumber(df,'MSRP'),
         Invoice = makeNumber(df,'Invoice'),
         PriceDiff = lambda _df: _df.MSRP - _df.Invoice
        )
)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,PriceDiff
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189,3608
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172,2059
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183,2343
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186,2896
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197,4741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186,2362
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186,2482
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190,2637
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180,1494
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186,2033

4. Use a function to calcuate the difference

In [106]:
def makeNumber(_df, colName):
    return (_df[colName]
            .str.replace('$','', regex=True)
            .str.replace(',','', regex=True)
            .astype('int')
    )

def priceDiff(_df):
    return _df.MSRP - _df.Invoice

(df
 .assign(
         MSRP = makeNumber(df,'MSRP'),
         Invoice = makeNumber(df,'Invoice'),
         PriceDiff = lambda _df: priceDiff(_df)
        )
)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,PriceDiff
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189,3608
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172,2059
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183,2343
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186,2896
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197,4741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186,2362
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186,2482
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190,2637
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180,1494
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186,2033

In [ ]:
4. PriceDiff percentage

In [117]:
def makeNumber(_df, colName):
    return (_df[colName]
            .str.replace('$','', regex=True)
            .str.replace(',','', regex=True)
            .astype('int')
    )

def priceDiffPct(_df):
    return (((_df.MSRP - _df.Invoice)/_df.MSRP)
            .mul(100)
            .round(1)
    )

(df
 .assign(
         MSRP = makeNumber(df,'MSRP'),
         Invoice = makeNumber(df,'Invoice'),
         PriceDiff = lambda _df: priceDiffPct(_df)
        )
)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,PriceDiff
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189,9.8
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172,8.6
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183,8.7
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186,8.7
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197,10.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186,5.8
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186,5.8
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190,5.8
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180,5.7
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186,5.8

## Creating a boolean value using assign

In [95]:
def makeNumber(_df, colName):
    return (_df[colName]
            .str.replace('$','', regex=True)
            .str.replace(',','', regex=True)
            .astype('int')
    )

(df
 .assign(
         MSRP = makeNumber(df,'MSRP'),
         Invoice = makeNumber(df,'Invoice'),
         PriceDiff = lambda _df: _df.MSRP - _df.Invoice,
         MSRPGreaterThanInvoice = lambda _df: _df.MSRP >= _df.Invoice
        )
)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,PriceDiff,MSRPGreaterThanInvoice
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189,3608,True
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172,2059,True
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183,2343,True
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186,2896,True
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197,4741,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186,2362,True
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186,2482,True
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190,2637,True
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180,1494,True
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186,2033,True

Are all values true in the new InvoiceGreaterThanInvoice column?

In [98]:
def makeNumber(_df, colName):
    return (_df[colName]
            .str.replace('$','', regex=True)
            .str.replace(',','', regex=True)
            .astype('int')
    )

(df
 .assign(
         MSRP = makeNumber(df,'MSRP'),
         Invoice = makeNumber(df,'Invoice'),
         PriceDiff = lambda _df: _df.MSRP - _df.Invoice,
         MSRPGreaterThanInvoice = lambda _df: _df.MSRP >= _df.Invoice
        )
 .MSRPGreaterThanInvoice
 .all()
)

True

In [99]:
(df
 .assign(
         MSRP = makeNumber(df,'MSRP'),
         Invoice = makeNumber(df,'Invoice'),
         PriceDiff = lambda _df: _df.MSRP - _df.Invoice,
         MSRPGreaterThanInvoice = lambda _df: _df.MSRP >= _df.Invoice
        )
 .dtypes
)

Make                       object
Model                      object
Type                       object
Origin                     object
DriveTrain                 object
MSRP                        int32
Invoice                     int32
EngineSize                float64
Cylinders                 float64
Horsepower                  int64
MPG_City                    int64
MPG_Highway                 int64
Weight                      int64
Wheelbase                   int64
Length                      int64
PriceDiff                   int32
MSRPGreaterThanInvoice       bool
dtype: object

In [100]:
(df
 .assign(
         MSRP = makeNumber(df,'MSRP'),
         Invoice = makeNumber(df,'Invoice'),
         PriceDiff = lambda _df: _df.MSRP - _df.Invoice,
         MSRPGreaterThanInvoice = lambda _df: _df.MSRP >= _df.Invoice
        )
 .MSRPGreaterThanInvoice
 .value_counts()
)

True    428
Name: MSRPGreaterThanInvoice, dtype: int64

In [105]:
(df
 .assign(
         MSRP = makeNumber(df,'MSRP'),
         Invoice = makeNumber(df,'Invoice'),
         PriceDiff = lambda _df: _df.MSRP - _df.Invoice,
         MSRPGreaterThanInvoice = lambda _df: _df.MSRP >= _df.Invoice
 )
 .query('MSRPGreaterThanInvoice == True')
 .MSRPGreaterThanInvoice
 .count()
)

428